FROM golang:1.22-alpine as builder

WORKDIR /app

COPY app/go.mod app/go.sum ./
RUN go mod download

COPY app ./
COPY app/.env .

RUN go build -o /bin/cron ./cmd/cron/main.go

FROM alpine:latest

COPY --from=builder /bin/cron /bin/cron

ENTRYPOINT ["/bin/cron"]
