version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=astrologer
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgres://nikita:helloworld111@postgres:5432/astrologer_service?sslmode=disable
    depends_on:
      - postgres
    command: ["./main"]